### ISSUE TITLE
vertaisarviointi

### ISSUE THREAD

**Issue by lxhelmer** [tovento/spell-checker#1]
Code downloaded 21.2   21:00

The whole project is of high quality and the code itself and the documentation was really pleasant to read. 

The structure of the project is clear and uniform. Good practices like one class/function per purpose are practiced.

The testing is extensive or at least seems to be, with the little knowledge about the inner workings of the algorithm I have. 
The tests on the main algorithm seem quite good with hand calculated comparisons.

The code seems to be quite fast and I wasn't able to find any unreasonably slow operations. Good job. 

Small fix: link in github testdoc for trie tests is [broken.](https://github.com/tovento/spell-checker/blob/main/src/tests/data_structures/trie/trie.py)

**Comment by tovento** [comment]
Thanks for the feedback! I have fixed the broken link and it should work now.
